name: ggnomics-upset
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy>=1.24
  - pandas>=2.0
  - scipy>=1.10
  - statsmodels>=0.14
  - matplotlib-base>=3.8
  - pytest>=8
  - pip:
      - plotnine==0.16.0a11
