#!/usr/bin/env python3
"""Render the Quarto vignettes to executed notebooks for the Sphinx site.

The Sphinx documentation includes the workflow guides as Jupyter notebooks via
nbsphinx. Those notebooks are committed *with their outputs* so that building
the docs (locally, in CI, or on ReadTheDocs) needs neither network access to
the Bioconductor/BiocPy data services nor the analysis stack.

This script drives::

    quarto render <vignette>.qmd --to ipynb

for each vignette, which executes the code against the real public datasets
(reusing Quarto's committed ``_freeze`` cache where the source is unchanged)
and embeds the resulting figures in the notebook. The output is then moved into
``docs/tutorials/`` and given the title Sphinx should show in the toctree.

Usage::

    python tools/build_tutorial_notebooks.py            # all vignettes
    python tools/build_tutorial_notebooks.py upset      # just one

Run it from anywhere; paths are resolved relative to the repository root.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
VIGNETTES = REPO_ROOT / "vignettes"
TUTORIALS = REPO_ROOT / "docs" / "tutorials"

# Vignettes that become tutorial pages, in the order the toctree lists them.
# index.qmd is deliberately excluded: it is the Quarto site's landing page and
# its role is filled by docs/index.md on the Sphinx side.
VIGNETTE_NAMES = [
    "getting-started",
    "single-cell-scranpy",
    "bulk-rnaseq",
    "upset",
    "multimodal",
    "specialized-plots",
    "plot-gallery",
]


def _quarto() -> str:
    """Locate the Quarto CLI."""
    found = shutil.which("quarto")
    if found:
        return found
    for candidate in ("/usr/local/bin/quarto", "/opt/quarto/bin/quarto"):
        if Path(candidate).exists():
            return candidate
    raise SystemExit("error: the `quarto` CLI was not found on PATH")


def _render(name: str, quarto: str) -> Path:
    """Render one vignette to ipynb and return the produced notebook path."""
    source = VIGNETTES / f"{name}.qmd"
    if not source.exists():
        raise SystemExit(f"error: {source} does not exist")

    env = dict(os.environ)
    env.setdefault("MPLBACKEND", "Agg")
    # Quarto executes through this interpreter; no Jupyter kernel is registered.
    env.setdefault("QUARTO_PYTHON", sys.executable)

    print(f"[notebooks] rendering {name}.qmd -> ipynb", flush=True)
    subprocess.run(
        [quarto, "render", f"{name}.qmd", "--to", "ipynb"],
        cwd=VIGNETTES,
        env=env,
        check=True,
    )

    # Quarto writes the notebook into the project output directory.
    for candidate in (VIGNETTES / "_site" / f"{name}.ipynb", VIGNETTES / f"{name}.ipynb"):
        if candidate.exists():
            return candidate
    raise SystemExit(f"error: quarto did not produce a notebook for {name}")


# Cross-references inside the vignettes point at Quarto sources. In the Sphinx
# tree the sibling pages are notebooks, and the API reference is generated by
# sphinx-apidoc rather than quartodoc, so both have to be redirected.
_LINK_REWRITES = [
    # The quartodoc reference index -> the sphinx-apidoc module reference.
    (re.compile(r"\]\(\.{0,2}/?reference/index\.qmd(#[^)]*)?\)"), "](../api/modules.rst)"),
    # datasets.yml is not copied into the Sphinx tree; link to it on GitHub.
    (
        re.compile(r"\]\(datasets\.yml\)"),
        "](https://github.com/MaximilianNuber/ggnomics/blob/main/vignettes/datasets.yml)",
    ),
    # Sibling vignettes -> sibling notebooks, preserving any fragment.
    (re.compile(r"\]\((?!https?:)([A-Za-z0-9._-]+)\.qmd(#[^)]*)?\)"), r"](\1.ipynb\2)"),
]


def _rewrite_links(notebook: Path) -> int:
    """Point .qmd cross-references at their Sphinx equivalents."""
    data = json.loads(notebook.read_text(encoding="utf-8"))
    changed = 0

    for cell in data.get("cells", []):
        if cell.get("cell_type") != "markdown":
            continue
        source = "".join(cell.get("source", []))
        rewritten = source
        for pattern, replacement in _LINK_REWRITES:
            rewritten = pattern.sub(replacement, rewritten)
        if rewritten != source:
            changed += 1
            cell["source"] = rewritten.splitlines(keepends=True)

    if changed:
        notebook.write_text(json.dumps(data, indent=1, ensure_ascii=False), encoding="utf-8")
        print(f"[notebooks]   rewrote links in {changed} markdown cell(s)")
    return changed


def _quarto_slug(heading: str) -> str:
    """Reproduce the anchor Quarto/pandoc generates for a heading.

    Lowercase, drop everything up to the first letter (so the "7." numbering
    prefix disappears), strip punctuation other than ``-`` and ``_``, and
    collapse whitespace runs into single hyphens.
    """
    text = heading.strip().lstrip("#").strip()
    text = re.sub(r"^[^A-Za-z]+", "", text)
    text = text.lower()
    text = re.sub(r"[^\w\s-]", "", text, flags=re.UNICODE)
    text = re.sub(r"[\s]+", "-", text)
    return re.sub(r"-{2,}", "-", text).strip("-")


def _nbsphinx_anchor(heading: str) -> str:
    """Reproduce the anchor nbsphinx generates.

    nbsphinx renders the heading's inline markup first, so backticks and
    emphasis markers are stripped, then spaces become hyphens. Case and the
    remaining punctuation (including the "13." numbering) are preserved.
    """
    text = heading.strip().lstrip("#").strip()
    text = text.replace("`", "")
    text = re.sub(r"(?<!\w)[*_]{1,2}(?=\S)", "", text)
    text = re.sub(r"(?<=\S)[*_]{1,2}(?!\w)", "", text)
    return re.sub(r"\s+", "-", text)


def _heading_anchors(notebook: Path) -> dict[str, str]:
    """Map each heading's Quarto anchor to the anchor nbsphinx will emit."""
    data = json.loads(notebook.read_text(encoding="utf-8"))
    mapping: dict[str, str] = {}
    for cell in data.get("cells", []):
        if cell.get("cell_type") != "markdown":
            continue
        for line in "".join(cell.get("source", [])).splitlines():
            if re.match(r"^#{1,6}\s+\S", line):
                mapping[_quarto_slug(line)] = _nbsphinx_anchor(line)
    return mapping


def retarget_fragments(notebooks: list[Path]) -> int:
    """Rewrite section fragments to the anchors nbsphinx actually generates.

    Quarto drops explicit ``{#id}`` attributes when converting to ipynb, and
    nbsphinx then builds its own anchors from the rendered heading text
    (``7.-PCA-on-the-VST-transformed-expression`` rather than
    ``pca-on-the-vst-transformed-expression``). Without this pass every
    cross-section link becomes an "undefined label" warning and a dead link.

    Substitution is literal on ``#<quarto-slug>)`` rather than regex-based on
    the whole link: nbsphinx anchors can contain parentheses (for example
    ``13.-Native-plot_pseudobulk_de(mode="upset")``), which no simple link
    pattern parses correctly. Quarto slugs never contain parentheses, so the
    literal form is unambiguous - and it is idempotent, because once a
    fragment has been rewritten the slug is no longer present.
    """
    anchors = {nb.stem: _heading_anchors(nb) for nb in notebooks}
    # Longest slugs first, so a slug that prefixes another cannot win.
    replacements = sorted(
        ((f"#{slug})", f"#{anchor})") for mapping in anchors.values() for slug, anchor in mapping.items() if slug),
        key=lambda pair: len(pair[0]),
        reverse=True,
    )

    total = 0
    for notebook in notebooks:
        data = json.loads(notebook.read_text(encoding="utf-8"))
        changed = False

        for cell in data.get("cells", []):
            if cell.get("cell_type") != "markdown":
                continue
            source = "".join(cell.get("source", []))
            rewritten = source
            for old, new_text in replacements:
                if old in rewritten:
                    rewritten = rewritten.replace(old, new_text)
            if rewritten != source:
                changed = True
                total += 1
                cell["source"] = rewritten.splitlines(keepends=True)

        if changed:
            notebook.write_text(json.dumps(data, indent=1, ensure_ascii=False), encoding="utf-8")

    if total:
        print(f"[notebooks] retargeted fragments in {total} markdown cell(s)")
    return 0


def _retitle(notebook: Path, title: str) -> None:
    """Ensure the notebook opens with a level-1 heading nbsphinx can use."""
    data = json.loads(notebook.read_text(encoding="utf-8"))
    cells = data.get("cells", [])

    def _is_h1(cell: dict) -> bool:
        if cell.get("cell_type") != "markdown":
            return False
        source = "".join(cell.get("source", []))
        return source.lstrip().startswith("# ")

    if not any(_is_h1(cell) for cell in cells[:2]):
        cells.insert(
            0,
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [f"# {title}\n"],
            },
        )
        data["cells"] = cells
        notebook.write_text(json.dumps(data, indent=1, ensure_ascii=False), encoding="utf-8")
        print(f"[notebooks]   added an H1 title: {title}")


def _title_for(name: str, notebook: Path) -> str:
    """Prefer the vignette's YAML title, falling back to the file name."""
    source = VIGNETTES / f"{name}.qmd"
    text = source.read_text(encoding="utf-8")
    if text.startswith("---"):
        end = text.find("\n---", 3)
        front_matter = text[3:end] if end != -1 else ""
        for line in front_matter.splitlines():
            if line.startswith("title:"):
                return line.split(":", 1)[1].strip().strip('"').strip("'")
    return name.replace("-", " ").capitalize()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "vignettes",
        nargs="*",
        default=None,
        help=f"vignette names to build (default: all of {', '.join(VIGNETTE_NAMES)})",
    )
    args = parser.parse_args(argv)

    names = args.vignettes or VIGNETTE_NAMES
    unknown = [n for n in names if n not in VIGNETTE_NAMES]
    if unknown:
        raise SystemExit(f"error: unknown vignette(s): {', '.join(unknown)}")

    quarto = _quarto()
    TUTORIALS.mkdir(parents=True, exist_ok=True)

    for name in names:
        produced = _render(name, quarto)
        destination = TUTORIALS / f"{name}.ipynb"
        shutil.move(str(produced), destination)
        _rewrite_links(destination)
        _retitle(destination, _title_for(name, destination))
        print(f"[notebooks] wrote {destination.relative_to(REPO_ROOT)}")

    # Fragment retargeting needs every notebook present, so it runs last and
    # always over the full set (a partial rebuild still has to see siblings).
    retarget_fragments(sorted(TUTORIALS.glob("*.ipynb")))

    print(f"\n[notebooks] {len(names)} notebook(s) up to date in docs/tutorials/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
