"""Sphinx configuration for the ggnomics documentation.

Follows the layout used across BiocPy packages (see, for example,
https://libscran.github.io/scranpy/): furo theme, MyST-Markdown sources, and an
API reference generated by ``sphinx-apidoc`` from the package docstrings.

ggnomics adds ``nbsphinx`` on top of that so the workflow guides ship as
executed Jupyter notebooks. Those notebooks are produced from the Quarto
sources in ``vignettes/`` with

    quarto render <vignette>.qmd --to ipynb

and are committed *with their outputs*, so this build never executes them (see
``nbsphinx_execute`` below) and needs neither network access nor the heavy
analysis stack.
"""

import os
import shutil
import sys

# -- Path setup --------------------------------------------------------------

__location__ = os.path.dirname(__file__)

# ggnomics uses a flat layout, so the package lives one level up.
sys.path.insert(0, os.path.abspath(os.path.join(__location__, "..")))

# -- Run sphinx-apidoc -------------------------------------------------------
# Run here rather than as a separate build step so that ReadTheDocs, which
# invokes sphinx-build directly, still gets a complete module reference.
# See https://github.com/readthedocs/readthedocs.org/issues/1139

output_dir = os.path.join(__location__, "api")
module_dir = os.path.join(__location__, "..", "ggnomics")

try:
    shutil.rmtree(output_dir)
except FileNotFoundError:
    pass

try:
    import sphinx
    from sphinx.ext import apidoc

    # Every public name is re-exported from ggnomics/__init__.py, so the
    # package page (see the automodule appended below) is the API reference.
    # The flat top-level modules are excluded so each object is documented
    # exactly once: documenting them twice makes sphinx emit duplicate object
    # descriptions and makes viewcode anchor its [docs] back-links to the
    # package name on the module page, where that anchor does not exist.
    #
    # Subpackages (ggnomics.upset, ggnomics.bulk, ggnomics.pca,
    # ggnomics.singlecell) keep their own pages: they are imported as modules
    # rather than flattened into the root namespace.
    _flat_modules = sorted(
        path.name
        for path in os.scandir(module_dir)
        if path.is_file() and path.name.endswith(".py") and path.name != "__init__.py"
    )
    excluded = [os.path.join(module_dir, name) for name in _flat_modules]
    excluded += [os.path.join(module_dir, pattern) for pattern in ("_*.py", "*/_*.py", "_backends")]

    # --implicit-namespaces is required: Sphinx 9's apidoc asserts when the
    # path it is given is itself a package. The side effect is that the
    # generated ggnomics.rst carries only a bare `py:module::` directive, so
    # the package page would document nothing - see the post-processing below.
    args = [
        "--implicit-namespaces",
        "--force",
        "--module-first",
        "--separate",
        "-o",
        output_dir,
        module_dir,
        *excluded,
    ]
    if tuple(sphinx.__version__.split(".")) < ("1", "7"):
        args = ["sphinx-apidoc"] + args

    apidoc.main(args)
except Exception as exc:  # pragma: no cover - build-time diagnostic
    import traceback

    print(f"Running `sphinx-apidoc` failed!\n{exc}")
    traceback.print_exc()

# ggnomics/__init__.py re-exports the whole public API and defines __all__, so
# `ggnomics.plot_umap` is the name users write and the name viewcode anchors
# its [docs] back-links to. Under --implicit-namespaces apidoc does not emit an
# automodule for the package itself, which would leave every one of those
# anchors dangling. Append it here so the package page is the public API
# reference it should be.
_package_rst = os.path.join(output_dir, "ggnomics.rst")
if os.path.exists(_package_rst):
    with open(_package_rst, encoding="utf-8") as handle:
        _content = handle.read()
    if ".. automodule:: ggnomics\n" not in _content:
        # apidoc writes a bare `py:module::` for the namespace; the automodule
        # below declares the same module, so drop it to avoid a duplicate.
        _content = _content.replace(".. py:module:: ggnomics\n", "", 1)
        _content += (
            "\nPublic API\n"
            "----------\n\n"
            ".. automodule:: ggnomics\n"
            "   :members:\n"
            "   :imported-members:\n"
            "   :show-inheritance:\n"
        )
        with open(_package_rst, "w", encoding="utf-8") as handle:
            handle.write(_content)


# -- General configuration ---------------------------------------------------

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.coverage",
    "sphinx.ext.doctest",
    "sphinx.ext.ifconfig",
    "sphinx.ext.intersphinx",
    "sphinx.ext.mathjax",
    "sphinx.ext.napoleon",
    "sphinx.ext.todo",
    "sphinx.ext.viewcode",
    "sphinx_autodoc_typehints",
    "sphinx_copybutton",
    "myst_parser",
    "nbsphinx",
]

templates_path = ["_templates"]

# Configure MyST-Parser
myst_enable_extensions = [
    "amsmath",
    "colon_fence",
    "deflist",
    "dollarmath",
    "html_image",
    "linkify",
    "replacements",
    "smartquotes",
    "substitution",
    "tasklist",
]

source_suffix = [".rst", ".md"]

master_doc = "index"

project = "ggnomics"
copyright = "2025, MaximilianNuber"
author = "MaximilianNuber"

try:
    from ggnomics import __version__ as version
except ImportError:
    version = ""

if not version or version.lower() == "unknown":
    try:
        from importlib.metadata import PackageNotFoundError
        from importlib.metadata import version as _pkg_version

        version = _pkg_version("ggnomics")
    except (ImportError, PackageNotFoundError):
        version = os.getenv("READTHEDOCS_VERSION", "unknown")

release = version

exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    ".venv",
    # Source images for the README, not documentation pages.
    "img",
    # Notebook checkpoints produced by Jupyter.
    "**.ipynb_checkpoints",
]

pygments_style = "sphinx"

todo_emit_warnings = True

# -- autodoc -----------------------------------------------------------------

autodoc_default_options = {
    "members": True,
    "undoc-members": False,
    "show-inheritance": True,
    "exclude-members": "__weakref__, __dict__, __str__, __module__, __init__",
}

autosummary_generate = True
# Left off: ggnomics/__init__.py re-exports the whole public API, and
# documenting those imports again duplicates every entry that already has a
# page under its defining module.
autosummary_imported_members = False

# ggnomics keeps typing.Optional/List in public signatures for 3.10 parity;
# render them as written rather than rewriting to PEP 604.
autodoc_typehints = "description"
always_document_param_types = True
typehints_defaults = "comma"

# Optional container backends must not be imported to build the docs. autodoc
# imports ggnomics itself (a real dependency), but anything that is only
# available behind an extra is mocked so a minimal docs environment works.
autodoc_mock_imports = [
    "anndata",
    "mudata",
    "singlecellexperiment",
    "summarizedexperiment",
    "biocframe",
    "marsilea",
    "umap",
    "sklearn",
    "statsmodels",
]

# ggnomics/__init__.py re-exports the whole public API. With the default
# viewcode_follow_imported_members=True, viewcode follows those re-exports and
# emits [docs] back-links anchored at `ggnomics.<name>`, while sphinx-apidoc
# documents the objects on their defining module's page as
# `ggnomics.<module>.<name>` - leaving every back-link broken. Anchor them
# where they are actually documented instead.
viewcode_follow_imported_members = False

napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False

# -- nbsphinx ----------------------------------------------------------------

# The notebooks in docs/tutorials/ are committed with their outputs, produced
# by `quarto render --to ipynb` against the real public datasets. Executing
# them again here would require network access and the full analysis stack, and
# would defeat the purpose of committing them.
nbsphinx_execute = "never"
nbsphinx_allow_errors = False
nbsphinx_prolog = """
.. raw:: html

    <div class="admonition note">
      <p class="admonition-title">Notebook</p>
      <p>
        This page is generated from a Quarto vignette executed against real
        public datasets. The source lives in
        <code>vignettes/</code> in the repository.
      </p>
    </div>
"""

# -- HTML output -------------------------------------------------------------

html_theme = "furo"

html_theme_options = {
    "sidebar_hide_name": False,
    "source_repository": "https://github.com/MaximilianNuber/ggnomics/",
    "source_branch": "main",
    "source_directory": "docs/",
}

html_static_path = ["_static"]
html_title = f"ggnomics {release}"
htmlhelp_basename = "ggnomics-doc"

# -- LaTeX output ------------------------------------------------------------

latex_elements = {}
latex_documents = [("index", "user_guide.tex", "ggnomics Documentation", "MaximilianNuber", "manual")]

# -- External mapping --------------------------------------------------------

python_version = ".".join(map(str, sys.version_info[0:2]))
intersphinx_mapping = {
    "python": ("https://docs.python.org/" + python_version, None),
    "numpy": ("https://numpy.org/doc/stable", None),
    "pandas": ("https://pandas.pydata.org/docs/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/reference", None),
    "plotnine": ("https://plotnine.org/", None),
    "anndata": ("https://anndata.readthedocs.io/en/stable/", None),
    "biocframe": ("https://biocpy.github.io/BiocFrame", None),
    "summarizedexperiment": ("https://biocpy.github.io/SummarizedExperiment", None),
    "singlecellexperiment": ("https://biocpy.github.io/SingleCellExperiment", None),
}
